/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMonthlyAnalysisRouteImport } from './routes/_authenticated/monthly-analysis'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedHormonesRouteImport } from './routes/_authenticated/hormones'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedDietRouteImport } from './routes/_authenticated/diet'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedFeedbackWeeklyRouteImport } from './routes/_authenticated/feedback.weekly'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminLibraryRouteImport } from './routes/_authenticated/admin.library'
import { Route as AuthenticatedAdminExercisesRouteImport } from './routes/_authenticated/admin.exercises'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as ApiPublicShareTokenRouteImport } from './routes/api/public/share.$token'
import { Route as ApiPublicShareOgTokenRouteImport } from './routes/api/public/share-og.$token'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonthlyAnalysisRoute =
  AuthenticatedMonthlyAnalysisRouteImport.update({
    id: '/monthly-analysis',
    path: '/monthly-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHormonesRoute = AuthenticatedHormonesRouteImport.update({
  id: '/hormones',
  path: '/hormones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDietRoute = AuthenticatedDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedFeedbackWeeklyRoute =
  AuthenticatedFeedbackWeeklyRouteImport.update({
    id: '/feedback/weekly',
    path: '/feedback/weekly',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLibraryRoute =
  AuthenticatedAdminLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExercisesRoute =
  AuthenticatedAdminExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicShareTokenRoute = ApiPublicShareTokenRouteImport.update({
  id: '/api/public/share/$token',
  path: '/api/public/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareOgTokenRoute = ApiPublicShareOgTokenRouteImport.update({
  id: '/api/public/share-og/$token',
  path: '/api/public/share-og/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet': typeof AuthenticatedDietRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/hormones': typeof AuthenticatedHormonesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/monthly-analysis': typeof AuthenticatedMonthlyAnalysisRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/coach': typeof ApiCoachRoute
  '/s/$token': typeof STokenRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/feedback/weekly': typeof AuthenticatedFeedbackWeeklyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/api/public/share-og/$token': typeof ApiPublicShareOgTokenRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet': typeof AuthenticatedDietRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/hormones': typeof AuthenticatedHormonesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/monthly-analysis': typeof AuthenticatedMonthlyAnalysisRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/coach': typeof ApiCoachRoute
  '/s/$token': typeof STokenRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/feedback/weekly': typeof AuthenticatedFeedbackWeeklyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/api/public/share-og/$token': typeof ApiPublicShareOgTokenRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diet': typeof AuthenticatedDietRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/hormones': typeof AuthenticatedHormonesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/monthly-analysis': typeof AuthenticatedMonthlyAnalysisRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/coach': typeof ApiCoachRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/_authenticated/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/feedback/weekly': typeof AuthenticatedFeedbackWeeklyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/api/public/share-og/$token': typeof ApiPublicShareOgTokenRoute
  '/api/public/share/$token': typeof ApiPublicShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/achievements'
    | '/admin'
    | '/challenges'
    | '/dashboard'
    | '/diet'
    | '/generate'
    | '/hormones'
    | '/messages'
    | '/monthly-analysis'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/ranking'
    | '/training'
    | '/admin/login'
    | '/api/coach'
    | '/s/$token'
    | '/admin/clients'
    | '/admin/exercises'
    | '/admin/library'
    | '/admin/messages'
    | '/admin/settings'
    | '/feedback/weekly'
    | '/admin/'
    | '/admin/clients/$id'
    | '/api/public/share-og/$token'
    | '/api/public/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/achievements'
    | '/challenges'
    | '/dashboard'
    | '/diet'
    | '/generate'
    | '/hormones'
    | '/messages'
    | '/monthly-analysis'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/ranking'
    | '/training'
    | '/admin/login'
    | '/api/coach'
    | '/s/$token'
    | '/admin/clients'
    | '/admin/exercises'
    | '/admin/library'
    | '/admin/messages'
    | '/admin/settings'
    | '/feedback/weekly'
    | '/admin'
    | '/admin/clients/$id'
    | '/api/public/share-og/$token'
    | '/api/public/share/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/_authenticated/diet'
    | '/_authenticated/generate'
    | '/_authenticated/hormones'
    | '/_authenticated/messages'
    | '/_authenticated/monthly-analysis'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/ranking'
    | '/_authenticated/training'
    | '/admin/login'
    | '/api/coach'
    | '/s/$token'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/exercises'
    | '/_authenticated/admin/library'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/settings'
    | '/_authenticated/feedback/weekly'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/clients/$id'
    | '/api/public/share-og/$token'
    | '/api/public/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiCoachRoute: typeof ApiCoachRoute
  STokenRoute: typeof STokenRoute
  ApiPublicShareOgTokenRoute: typeof ApiPublicShareOgTokenRoute
  ApiPublicShareTokenRoute: typeof ApiPublicShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monthly-analysis': {
      id: '/_authenticated/monthly-analysis'
      path: '/monthly-analysis'
      fullPath: '/monthly-analysis'
      preLoaderRoute: typeof AuthenticatedMonthlyAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hormones': {
      id: '/_authenticated/hormones'
      path: '/hormones'
      fullPath: '/hormones'
      preLoaderRoute: typeof AuthenticatedHormonesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diet': {
      id: '/_authenticated/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticatedDietRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/feedback/weekly': {
      id: '/_authenticated/feedback/weekly'
      path: '/feedback/weekly'
      fullPath: '/feedback/weekly'
      preLoaderRoute: typeof AuthenticatedFeedbackWeeklyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/library': {
      id: '/_authenticated/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AuthenticatedAdminLibraryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exercises': {
      id: '/_authenticated/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AuthenticatedAdminExercisesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/share/$token': {
      id: '/api/public/share/$token'
      path: '/api/public/share/$token'
      fullPath: '/api/public/share/$token'
      preLoaderRoute: typeof ApiPublicShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share-og/$token': {
      id: '/api/public/share-og/$token'
      path: '/api/public/share-og/$token'
      fullPath: '/api/public/share-og/$token'
      preLoaderRoute: typeof ApiPublicShareOgTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminExercisesRoute: typeof AuthenticatedAdminExercisesRoute
  AuthenticatedAdminLibraryRoute: typeof AuthenticatedAdminLibraryRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminExercisesRoute: AuthenticatedAdminExercisesRoute,
  AuthenticatedAdminLibraryRoute: AuthenticatedAdminLibraryRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDietRoute: typeof AuthenticatedDietRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedHormonesRoute: typeof AuthenticatedHormonesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMonthlyAnalysisRoute: typeof AuthenticatedMonthlyAnalysisRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedFeedbackWeeklyRoute: typeof AuthenticatedFeedbackWeeklyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDietRoute: AuthenticatedDietRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedHormonesRoute: AuthenticatedHormonesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMonthlyAnalysisRoute: AuthenticatedMonthlyAnalysisRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedFeedbackWeeklyRoute: AuthenticatedFeedbackWeeklyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiCoachRoute: ApiCoachRoute,
  STokenRoute: STokenRoute,
  ApiPublicShareOgTokenRoute: ApiPublicShareOgTokenRoute,
  ApiPublicShareTokenRoute: ApiPublicShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
